package br.com.dompagamentos.domain.model.enums;

public enum PaymentStatus {
    PENDING,
    PROCESSING,
    CONFIRMED,
    RECEIVED,
    OVERDUE,
    REFUNDED,
    REFUND_REQUESTED,
    CHARGEBACK_REQUESTED,
    CHARGEBACK_DISPUTE,
    AWAITING_CHARGEBACK_REVERSAL,
    DUNNING_REQUESTED,
    DUNNING_RECEIVED,
    CANCELLED
}
